name: ci_pipeline

on:
  push:
    branches:
      - "add-cicd"

env:
  CHECK_VERSION: mvn -B help:evaluate -Dexpression=project.version -q -DforceStdout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Check actual version
        id: actualversion
        run: echo "VERSION="${{env.CHECK_VERSION}}
      -
        name: Build with Maven
        run: mvn -B validate -DbumpMajor clean package --file pom.xml
      -
        name: Check new version
        id: newversion
        run: echo ::set-output name=ver::mvn help:evaluate -Dexpression=project.version -q -DforceStdout
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/java-filmorate:${{steps.version.outputs}}
